=== draker94/java-epam-task3/data/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://training.by/greenhouse/namespaces"
        xmlns:tns="https://training.by/greenhouse/namespaces"
        elementFormDefault="qualified">
    <element name="greenhouse">
        <complexType>
            <sequence>
                <element name="plant" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="soil">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="подзолистая"/>
                                        <enumeration value="грунтовая"/>
                                        <enumeration value="дерново-подзолистая"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="origin" type="string"/>
                            <element name="visual-parameters">
                                <complexType>
                                    <sequence>
                                        <element name="stem-color" type="string"/>
                                        <element name="leaf-color" type="string"/>
                                        <element name="average-size" type="tns:valid-min-value"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="growing-tips">
                                <complexType>
                                    <sequence>
                                        <element name="temp" type="tns:valid-temperature"/>
                                        <element name="lighting" type="boolean"/>
                                        <element name="irrigation" type="tns:valid-min-value"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="multiplying">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="листьями"/>
                                        <enumeration value="черенками"/>
                                        <enumeration value="семенами"/>
                                    </restriction>
                                </simpleType>
                            </element>
                        </sequence>
                        <attribute name="id" use="required">
                            <simpleType>
                                <restriction base="ID">
                                    <pattern value="f[0-9]{1,4}"/>
                                </restriction>
                            </simpleType>
                        </attribute>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
    <simpleType name="valid-min-value">
        <restriction base="integer">
            <minInclusive value="1"/>
        </restriction>
    </simpleType>
    <simpleType name="valid-temperature">
        <restriction base="integer">
            <minInclusive value="-40"/>
            <maxInclusive value="40"/>
        </restriction>
    </simpleType>
</schema>

=== draker94/java-epam-task3/data/greenhouseWrite.xml
<?xml version="1.0" encoding="UTF-8"?>
<greenhouse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://training.by/greenhouse/namespaces" xsi:schemaLocation="https://training.by/greenhouse/namespaces greenhouse.xsd">
<plant id="f1">
	<name>Пион</name>
	<soil>подзолистая</soil>
	<origin>Китай</origin>
<visual-parameters>
	<stem-color>Оливковый</stem-color>
	<leaf-color>Красный</leaf-color>
	<average-size>18</average-size>
</visual-parameters>
<growing-tips>
	<temp>15</temp>
	<lighting>true</lighting>
	<irrigation>12500</irrigation>
</growing-tips>
	<multiplying>черенками</multiplying>
</plant>
<plant id="f2">
	<name>Пшеница</name>
	<soil>дерново-подзолистая</soil>
	<origin>Армения</origin>
<visual-parameters>
	<stem-color>Золотистый</stem-color>
	<leaf-color>Пшеничный</leaf-color>
	<average-size>150</average-size>
</visual-parameters>
<growing-tips>
	<temp>25</temp>
	<lighting>true</lighting>
	<irrigation>4000</irrigation>
</growing-tips>
	<multiplying>семенами</multiplying>
</plant>
<plant id="f3">
	<name>Мирабилис</name>
	<soil>грунтовая</soil>
	<origin>Мексика</origin>
<visual-parameters>
	<stem-color>Красный</stem-color>
	<leaf-color>Малиновый</leaf-color>
	<average-size>45</average-size>
</visual-parameters>
<growing-tips>
	<temp>-20</temp>
	<lighting>false</lighting>
	<irrigation>7000</irrigation>
</growing-tips>
	<multiplying>листьями</multiplying>
</plant>
</greenhouse>
